backend:
  name: git-gateway
  branch: master
media_folder: "src/_images/uploads"
public_folder: "images/uploads"

collections:
  - label: "Strony"
    name: "pages"
    delete: false
    files:
      - label: "Główna"
        name: "main"
        file: "src/_data/main.yml"
        fields:
          - label: "Terapia"
            name: "terapia"
            widget: "object"
            fields:
              - {label: "Tytuł", name: "title", widget: "string"}
              - {label: "Opis", name: "description", widget: "text"}
